import { useEffect, useMemo, useState } from "react";
import { invokeFunction } from "../lib/api";

type RelayState="NOT_CONFIGURED"|"VERIFICATION_PENDING"|"ACTIVE"|"ERROR"|"REVOKED";
type SourceProvider="gmail"|"outlook"|"proton"|"other";
type CatalogItem={id:string;display_name:string;sender_domains:string[];country_code:string|null;sort_order:number};
type RelaySource={id:string;provider:SourceProvider;label:string;state:RelayState;gmailConfirmationUrl?:string|null;gmailConfirmationCode?:string|null;lastReceivedAt?:string|null;lastFinancialEventAt?:string|null};
type RelayResponse={state:RelayState;address?:string;aliasHint?:string|null;lastReceivedAt?:string|null;lastFinancialEventAt?:string|null;domain?:string;sources?:RelaySource[];catalog?:CatalogItem[]};
const labels:Record<RelayState,string>={NOT_CONFIGURED:"No configurado",VERIFICATION_PENDING:"Verificacion pendiente",ACTIVE:"Activo",ERROR:"Error",REVOKED:"Revocado"};
const providerNames:Record<SourceProvider,string>={gmail:"Gmail",outlook:"Outlook / Hotmail",proton:"Proton Mail",other:"Otro correo"};

export function EmailRelayCard(){
  const [state,setState]=useState<RelayResponse>({state:"NOT_CONFIGURED",sources:[]}); const [provider,setProvider]=useState<SourceProvider>("gmail");
  const [sourceLabel,setSourceLabel]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const load=async()=>{try{const data=await invokeFunction<RelayResponse>("email-relay-settings",{action:"state"});setState((prev)=>{const next:RelayResponse={...data};if(data.state==="REVOKED"){delete next.address;}else if(prev.address!==undefined){next.address=prev.address;}return next;});}catch{setMessage("No fue posible consultar el estado del correo automatico.");}};
  useEffect(()=>{void load();},[]);
  const domains=useMemo(()=>[...new Set((state.catalog ?? []).filter((x)=>selected.includes(x.id)).flatMap((x)=>x.sender_domains))],[state.catalog,selected]);
  const gmailFilter=domains.length?`from:(${domains.map((x)=>`@${x}`).join(" OR ")})`:"Selecciona tus entidades para generar el filtro.";
  const generate=async(action:"generate"|"rotate")=>{setBusy(true);setMessage(null);try{const data=await invokeFunction<RelayResponse>("email-relay-settings",{action});setState((prev)=>{const next:RelayResponse={...prev,...data,sources:data.sources ?? []};if(prev.catalog!==undefined){next.catalog=prev.catalog;}else{delete next.catalog;}if(prev.domain!==undefined){next.domain=prev.domain;}else{delete next.domain;}return next;});setMessage("Direccion privada creada. Usa esta misma direccion en Gmail, Outlook, Proton Mail o cualquier otro correo que quieras conectar.");}catch{setMessage("No fue posible crear la direccion privada. Verifica que tu suscripcion este activa.");}finally{setBusy(false);}};
  const revoke=async()=>{setBusy(true);try{await invokeFunction("email-relay-settings",{action:"revoke"});await load();setMessage("Direccion y fuentes revocadas.");}finally{setBusy(false);}};
  const addSource=async()=>{setBusy(true);setMessage(null);try{await invokeFunction("email-relay-settings",{action:"add_source",provider,label:sourceLabel.trim()||providerNames[provider]});setSourceLabel("");await load();setMessage(`${providerNames[provider]} agregado. Configura el reenvio hacia la misma direccion privada de CapitalFlow.`);}catch{setMessage("No fue posible agregar esta fuente de correo.");}finally{setBusy(false);}};
  const revokeSource=async(sourceId:string)=>{setBusy(true);try{await invokeFunction("email-relay-settings",{action:"revoke_source",sourceId});await load();setMessage("Fuente de correo revocada sin afectar las demas.");}finally{setBusy(false);}};
  const copy=async(value:string)=>{await navigator.clipboard.writeText(value);setMessage("Direccion copiada.");};
  const providerGuide=provider==="gmail"?<ol><li>En Gmail abre Configuracion, Reenvio y agrega la direccion privada de CapitalFlow.</li><li>CapitalFlow detectara el correo de confirmacion de Gmail.</li><li>Confirma el reenvio y crea un filtro con tus entidades financieras.</li></ol>:provider==="outlook"?<ol><li>En Outlook abre Configuracion, Correo, Reglas.</li><li>Crea una regla con tus remitentes financieros y elige Reenviar o Redirigir a la misma direccion privada.</li><li>Guarda la regla y espera el primer correo.</li></ol>:provider==="proton"?<ol><li>En Proton Mail abre la configuracion de reenvio o filtros de tu plan.</li><li>Reenvia los avisos financieros a la misma direccion privada de CapitalFlow.</li><li>Espera el primer correo para confirmar que la fuente esta activa.</li></ol>:<ol><li>Crea una regla de reenvio hacia la misma direccion privada.</li><li>Limita la regla a remitentes financieros cuando tu proveedor lo permita.</li><li>Espera el primer correo para confirmar la conexion.</li></ol>;
  return <article className="integration-card" style={{display:"grid",gap:"1rem"}} aria-labelledby="email-relay-title">
    <div><h2 id="email-relay-title">Correo financiero automatico</h2><p className="muted">Una sola direccion privada de CapitalFlow puede recibir reenvios desde varios correos: Gmail, Outlook, Proton Mail y otros. Todos llegan al mismo punto de ingesta y al mismo parser financiero.</p></div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><strong>Estado general:</strong><span>{labels[state.state]}</span>{state.lastReceivedAt?<span className="muted">Ultimo correo: {new Date(state.lastReceivedAt).toLocaleString()}</span>:null}</div>
    {state.address?<div><strong>Direccion compartida para todos tus correos</strong><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><code style={{wordBreak:"break-all"}}>{state.address}</code><button type="button" onClick={()=>void copy(state.address!)}>Copiar</button></div><p className="muted">Usa exactamente esta misma direccion como destino de reenvio en cada proveedor que agregues.</p></div>:state.aliasHint?<p>Direccion configurada: <code>cf+{state.aliasHint}@{state.domain ?? "dominio-de-ingesta"}</code>. Por seguridad el token completo solo se muestra al crear o rotar la direccion.</p>:null}
    {state.state==="NOT_CONFIGURED"||state.state==="REVOKED"?<button type="button" disabled={busy} onClick={()=>void generate("generate")}>Generar direccion privada compartida</button>:<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" disabled={busy} onClick={()=>void generate("rotate")}>Rotar direccion</button><button type="button" disabled={busy} onClick={()=>void revoke()}>Revocar toda la ingesta por correo</button></div>}
    {state.aliasHint||state.address?<section style={{display:"grid",gap:10}}><h3>Correos conectados</h3>
      {(state.sources ?? []).length?<div style={{display:"grid",gap:8}}>{(state.sources ?? []).map((source)=><div key={source.id} style={{border:"1px solid var(--border, #ddd)",padding:10,borderRadius:8}}><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><strong>{source.label}</strong><span>{providerNames[source.provider]}</span><span>{labels[source.state]}</span><button type="button" disabled={busy} onClick={()=>void revokeSource(source.id)}>Revocar esta fuente</button></div>{source.lastReceivedAt?<small>Ultimo correo: {new Date(source.lastReceivedAt).toLocaleString()}</small>:null}{source.gmailConfirmationUrl?<p><a href={source.gmailConfirmationUrl} target="_blank" rel="noreferrer">Abrir confirmacion segura de Gmail</a>{source.gmailConfirmationCode?<>. Codigo: <code>{source.gmailConfirmationCode}</code></>:null}</p>:null}</div>)}</div>:<p className="muted">Aun no has registrado fuentes. Puedes agregar varias y todas usaran la misma direccion.</p>}
      <div style={{display:"grid",gap:8}}><strong>Agregar otro correo</strong><label>Proveedor<select value={provider} onChange={(e)=>setProvider(e.target.value as SourceProvider)} disabled={busy} style={{display:"block",marginTop:6}}><option value="gmail">Gmail</option><option value="outlook">Outlook / Hotmail</option><option value="proton">Proton Mail</option><option value="other">Otro</option></select></label><label>Nombre opcional<input value={sourceLabel} onChange={(e)=>setSourceLabel(e.target.value)} placeholder={`${providerNames[provider]} personal`} maxLength={80} style={{display:"block",marginTop:6}} /></label><button type="button" disabled={busy} onClick={()=>void addSource()}>Agregar fuente</button></div>
      <div><strong>Configura el reenvio</strong>{providerGuide}</div>
      <strong>Entidades habituales</strong><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{(state.catalog ?? []).map((item)=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={(e)=>setSelected((prev)=>e.target.checked?[...prev,item.id]:prev.filter((x)=>x!==item.id))}/>{" "}{item.display_name}</label>)}</div>
      {provider==="gmail"?<div><strong>Filtro sugerido de Gmail</strong><pre style={{whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{gmailFilter}</pre>{domains.length?<button type="button" onClick={()=>void copy(gmailFilter)}>Copiar filtro</button>:null}</div>:null}
      <p className="muted">No conectas la API ni compartes contrasenas. Gmail, Outlook y Proton son fuentes del mismo relay; no se habilitan como proveedores OAuth de CapitalFlow.</p>
    </section>:null}
    {state.state==="ACTIVE"?<p><strong>CapitalFlow esta recibiendo movimientos por correo automaticamente.</strong></p>:state.state==="VERIFICATION_PENDING"?<p>La direccion esta lista. El estado cambiara cuando llegue correo correctamente.</p>:null}
    {message?<p role="status">{message}</p>:null}
  </article>;
}
