import test from "node:test"; import assert from "node:assert/strict";
import { buildRelayPayload, detectForwardingProvider, sign, validBackendUrl } from "./src/index.mjs";
test("worker signs deterministic HMAC",async()=>{const a=await sign("secret","1700000000","123e4567-e89b-12d3-a456-426614174000","{}");const b=await sign("secret","1700000000","123e4567-e89b-12d3-a456-426614174000","{}");assert.equal(a,b);assert.match(a,/^[0-9a-f]{64}$/);});
test("worker captures metadata and source hint",async()=>{const bytes=new TextEncoder().encode("Subject: Compra\r\n\r\nCOP 12.500");const headers=new Headers({from:"Bank <bank@example.com>",subject:"Compra","message-id":"<1@example.com>","x-google-smtp-source":"abc"});const message={rawSize:bytes.byteLength,raw:new Response(bytes).body,to:"cf+aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@ingest.example.com",from:"sender@example.com",headers};const p=await buildRelayPayload(message);assert.equal(p.subject,"Compra");assert.equal(p.forwardingProviderHint,"gmail");assert.match(p.rawSha256,/^[0-9a-f]{64}$/);assert.ok(p.rawMimeBase64.length>0);});
test("worker recognizes Outlook forwarding infrastructure",()=>{assert.equal(detectForwardingProvider(new Headers({received:"from mail.protection.outlook.com by mx.example"})),"outlook");});
test("worker recognizes Proton forwarding infrastructure",()=>{assert.equal(detectForwardingProvider(new Headers({received:"from mail.protonmail.ch by mx.example"})),"proton");});
test("worker keeps unknown forwarding infrastructure as other",()=>{assert.equal(detectForwardingProvider(new Headers({received:"from mx.example.net"})),"other");});

test("worker validates only the configured HTTPS Supabase gateway shape",()=>{assert.equal(validBackendUrl("https://xxmbqbnryhvybhlwivgq.supabase.co/functions/v1/email-relay-ingest"),true);assert.equal(validBackendUrl("http://xxmbqbnryhvybhlwivgq.supabase.co/functions/v1/email-relay-ingest"),false);assert.equal(validBackendUrl("https://evil.example/functions/v1/email-relay-ingest"),false);});
test("provider hint remains a hint, not worker authentication",()=>{assert.equal(detectForwardingProvider(new Headers({"x-google-smtp-source":"spoofed"})),"gmail");assert.equal(detectForwardingProvider(new Headers({"x-gm-message-state":"spoofed"})),"gmail");});
test("worker rejects oversize raw message before base64 payload",async()=>{const message={rawSize:524289,raw:new Response("x").body,to:"cf+aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@ingest.example.com",from:"sender@example.com",headers:new Headers()};await assert.rejects(()=>buildRelayPayload(message),/relay_message_too_large/);});
